name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set up API Authentication
      run: |
        $apiUrl = "https://my.serverspace.com.tr/api"
        $apiKey = "${{ secrets.API_KEY }}"  # GitHub Secrets'tan API anahtarını alın
        $headers = @{
          "Authorization" = "Bearer $apiKey"
          "Content-Type"  = "application/json"
        }

    - name: Create VDS
      run: |
        $body = @{
          "name" = "MyVDS"
          "plan" = "basic"  # Kullanmak istediğiniz plan
        } | ConvertTo-Json

        Invoke-RestMethod -Uri "$apiUrl/vds" -Method Post -Headers $headers -Body $body

    - name: Check VDS Status
      run: |
        $response = Invoke-RestMethod -Uri "$apiUrl/vds/my-vds-id" -Method Get -Headers $headers
        Write-Host "VDS Status: $($response.status)"
